# Generated by Django 4.0.4 on 2022-05-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanh',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sanhs/%Y/%m'),
        ),
    ]
