# Generated by Django 4.0.4 on 2022-05-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoi', '0002_alter_sanh_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaisanh',
            name='gia',
        ),
        migrations.AddField(
            model_name='loaisanh',
            name='gia_cuoi_tuan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loaisanh',
            name='gia_sang',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loaisanh',
            name='gia_toi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loaisanh',
            name='gia_trua',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Gia',
        ),
    ]
