# Generated by Django 4.0.4 on 2022-05-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoi', '0003_remove_loaisanh_gia_loaisanh_gia_cuoi_tuan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanh',
            name='ghi_chu',
        ),
    ]
