# Generated by Django 4.0.4 on 2022-05-07 14:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoi', '0004_remove_sanh_ghi_chu'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanh',
            name='ghi_chu',
            field=ckeditor.fields.RichTextField(default=123),
            preserve_default=False,
        ),
    ]
