# Generated by Django 4.0.4 on 2022-05-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoi', '0007_dichvu_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dichvu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dichvus/%Y/%m'),
        ),
    ]
