# Generated by Django 4.0.4 on 2022-05-15 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoi', '0009_user_is_customer_user_is_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiecCuoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sl_ban', models.IntegerField()),
                ('ngay_to_chuc', models.DateTimeField(auto_now=True)),
                ('dichvus', models.ManyToManyField(to='NhaHangTiecCuoi.dichvu')),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NhaHangTiecCuoi.menu')),
                ('sanh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NhaHangTiecCuoi.sanh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sanh', 'ngay_to_chuc')},
            },
        ),
    ]
