# Generated by Django 4.0.4 on 2022-05-15 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoi', '0010_tieccuoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tieccuoi',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NhaHangTiecCuoi.menu'),
        ),
        migrations.AlterField(
            model_name='tieccuoi',
            name='sanh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NhaHangTiecCuoi.sanh'),
        ),
    ]
