# Generated by Django 4.0.4 on 2022-05-18 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoi', '0012_alter_tieccuoi_ngay_to_chuc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tieccuoi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tieccuois', to=settings.AUTH_USER_MODEL),
        ),
    ]
