# Generated by Django 4.0.4 on 2022-05-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoi', '0013_alter_tieccuoi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tieccuoi',
            name='ten_chu_re',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='tieccuoi',
            name='ten_co_dau',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
