# Generated by Django 4.0.4 on 2022-05-20 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoi', '0014_tieccuoi_ten_chu_re_tieccuoi_ten_co_dau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('tieccuoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='NhaHangTiecCuoi.tieccuoi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
