# Generated by Django 4.0.4 on 2022-05-20 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoi', '0016_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tieccuoi',
            name='ten_chu_re',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tieccuoi',
            name='ten_co_dau',
            field=models.CharField(max_length=100),
        ),
    ]
