# Generated by Django 4.0.4 on 2022-05-21 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NhaHangTiecCuoi', '0017_alter_report_user_alter_tieccuoi_ten_chu_re_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('thanh_tien', models.FloatField(default=0)),
                ('tieccuoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitiethoadon', to='NhaHangTiecCuoi.tieccuoi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('chi_tiet_hoa_don', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hoadon', to='NhaHangTiecCuoi.chitiethoadon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
